"""
E1 — Core validity & tightness. Self-contained configuration.

This file is the single source of truth for the E1 sweep (E1a/E1b/E1c/E1d).
It deliberately does NOT import from the root config.py: the root config
describes the workshop GPT-Neo pipeline (seed 0-2, 1024 tokens, epoch sweep
[1,3,5,10]) and must keep describing it so the existing results stay
reproducible. E1 is a separate, scaled-up experiment with its own axes.

Root-level code that E1 *does* reuse (imported, never duplicated):
    metrics/compute_metrics.py  -- KL(score-space), Pinsker/BH, AUROC, TPR@FPR, Adv, TV
    signals/s_{loss,ref,zlib,mink}.py
    data/membership_assignment.py -- make_split / save_split / load_split
"""

from pathlib import Path

# Paths

E1_DIR = Path(__file__).parent.resolve()
ROOT = E1_DIR.parent

# Corpus pools and frozen membership splits, one subdirectory per corpus.
# Kept separate from the root raw_data/*.jsonl files (workshop seed 0-2 Enron
# splits) so regenerating E1 splits cannot clobber existing results.
E1_DATA_DIR = ROOT / "raw_data" / "e1"

# Everything produced by an E1 run lives under runs/<run_id>/ (see runspec.py).
E1_RUNS_DIR = ROOT / "runs"

# Per-token log-prob caches (.npz), keyed by run_id + reference model.
E1_CACHE_DIR = ROOT / "cache"

# Assembled metric tables and figures.
E1_RESULTS_DIR = E1_DIR / "results"
E1_FIGURES_DIR = E1_DIR / "figures"
E1_LOG_DIR = E1_DIR / "logs"


# Fixed hyperparameters (extension.md: "so the tables don't repeat them")

SEED = 42                    # one seed everywhere; uncertainty comes from bootstrap CIs
MAX_SEQ_LEN = 256            # truncated at load time; pools stay tokenized at 1024 on disk
LEARNING_RATE = 5e-5         # E2 sweeps this; E1 holds it fixed
WEIGHT_DECAY = 0.01
WARMUP_STEPS = 0
EFFECTIVE_BATCH = 32         # per-device batch is model-dependent; grad-accum makes up the rest

# Checkpoints are written at these epochs. One training run yields all of them,
# which is why the 9 E1a runs cover 63 evaluable checkpoints.
EPOCH_GRID = [1, 2, 3, 5, 10, 15, 20]

# Membership protocol. N_NONMEMBERS is fixed across all N so that the
# non-member score distribution is identical for every corpus size.
CORPUS_SIZES = [500, 2_000, 6_000]
N_NONMEMBERS = 2_000
N_DEFAULT = 2_000
POOL_SIZE = 10_000           # per corpus; enron pool already exists at this size


# Experiment grid

# E1a — full validity grid on Enron.
E1A = dict(
    models=["pythia-70m", "pythia-160m", "pythia-410m"],
    corpora=["enron"],
    corpus_sizes=CORPUS_SIZES,
)

# E1b — cross-domain validity at fixed N.
# 'news' is MUST (clean-room, zero pretraining contamination);
# 'legal' is RECOMMENDED and is the designated cut if Week 1 slips.
E1B = dict(
    models=["pythia-70m", "pythia-160m", "pythia-410m"],
    corpora=["news", "legal"],
    corpus_sizes=[N_DEFAULT],
)

# E1c — attack evaluation over every checkpoint produced by E1a + E1b.
E1C_ATTACKS = ["loss", "ref", "zlib", "mink", "minkpp", "rmia", "neighborhood"]

# E1d — SPV-MIA, headline config only (needs an extra fine-tune per target).
E1D = dict(
    model="pythia-410m",
    corpus="enron",
    n_members=N_DEFAULT,
    epochs=[3, 10, 20],
)


# Attack hyperparameters

MIN_K_FRACTION = 0.20        # matches root config; Min-K% and Min-K%++ share it

# RMIA: population sequences used to build the reference score distribution,
# and the likelihood-ratio threshold gamma from Zarifzadeh et al.
RMIA = dict(
    n_population=2_000,      # drawn from the eval split, disjoint from members/nonmembers
    gamma=1.0,
)

# Neighborhood attack: z neighbours per sequence, generated by masked-token
# substitution. n_neighbors drives eval cost linearly -- 25 is the paper's
# setting and already multiplies the E1c forward passes by 26.
NEIGHBORHOOD = dict(
    n_neighbors=25,
    mask_model="roberta-base",
    replacement_frac=0.10,
    batch_size=32,
)

# Primary signal for the headline validity claim.
PRIMARY_SIGNAL = "ref"


# Metrics

FPR_THRESHOLDS = [0.01, 0.001]

# Histogram bins for empirical TV and the score-space KL.
#
# The workshop pipeline uses 500 (root config.py). At the E1 pool sizes
# (2000-6000 members vs 2000 non-members) that is far too many: each bin holds
# a handful of samples and the plug-in KL is severely upward-biased. Measured
# on Gaussian pairs with known true KL, mean over 40 replicates at n=2000/2000:
#
#   true KL   10 bins   20 bins   100 bins   500 bins
#     0.020     0.027     0.036      0.113      0.516   (26x)
#     0.125     0.135     0.155      0.260      0.742   (6x)
#     0.500     0.512     0.560      0.791      1.547   (3x)
#     2.000     2.320     2.586      3.283      4.943   (2.5x)
#
# An inflated KL inflates the ceiling, so "no attack exceeds the bound" passes
# trivially and the tightness gap is an artifact of the bin count rather than a
# property of the attack. Both are RQ1 headline numbers, so this matters.
#
# Fewer bins is not automatically better: coarsening can only *reduce* KL
# (data processing), while the empirical advantage is computed on the raw
# continuous scores, so too few bins can push the bound below Adv and
# manufacture a violation. Measured over 60 replicates x 9 separations x 4
# score-distribution shapes (Gaussian equal/unequal variance, bimodal members,
# unequal pool sizes), false violations occur at 10 bins and vanish from 15 on.
#
# 20 bins is the smallest count with zero false violations and a positive
# safety margin in every case tested. test_e1.py pins both halves of this.
TV_N_BINS = 20

# Recomputed at these bin counts too, and written to the metrics table as
# kl_bins_<b> columns, so the paper can show the conclusion is not an artifact
# of one arbitrary choice.
KL_BIN_SENSITIVITY = [15, 20, 30, 50]

BOOTSTRAP_N = 1_000          # resamples for every CI (extension.md correction #1)
BOOTSTRAP_CI = 0.95

# Pinsker is tighter below this KL, Bretagnolle-Huber above it. Exact crossover
# is the nonzero root of KL/2 = 1 - exp(-KL); see stats.py::pinsker_bh_crossover.
KL_CROSSOVER = 1.5936242600400400


# Infrastructure

# Private HF Hub repo used as the checkpoint/cache sink, so a Kaggle session
# dying at 11h59 costs at most one epoch. Set HF_REPO_ID here (or override with
# the E1_HF_REPO environment variable); the token must be supplied separately
# as a Kaggle secret named HF_TOKEN. None disables all Hub I/O and falls back
# to local-only checkpointing.
HF_REPO_ID = None            # e.g. "mohamedjalalbaim/mia-e1-checkpoints"

# fp16 on P100 (no bf16 support on sm_60). Overridden per platform in models.py.
DEFAULT_DTYPE = "fp16"

# Columns written by eval_e1.py. Every metric column has a matching
# _ci_lo/_ci_hi pair produced by the bootstrap.
E1_METRIC_COLUMNS = [
    "run_id", "model", "corpus", "n_members", "epochs", "lr", "seed", "attack",
    "auroc", "tpr_at_fpr_1pct", "tpr_at_fpr_01pct",
    "adv", "tv_empirical",
    "kl_score_space", "pinsker", "bh", "bound",
    "tightness_gap", "adv_over_bound",
    "perplexity", "next_token_acc",
    "n_members_scored", "n_nonmembers_scored",
]
